// Generated by https://quicktype.io
export interface TipoResponse {
    page:        number;
    per_page:    number;
    total:       number;
    total_pages: number;
    data:        Tipo[];

}
export interface Tipo {
    id:     number;
    nombre: string;
}
