// Generated by https://quicktype.io

export interface Expedientes {
    id:           number;
    fecha:        string;
    numero:       string;
    materia:      string;
    estado:       boolean;
    responsable:  string;
    responsable2: null | string;
    descripcion:  string;
    condicion:    Condicion;
    precio:       number;
    consejeria:   string;
    expediente:   Expediente;
}

export enum Condicion {
    Confidencial = "confidencial",
    EnSeguimiento = "en seguimiento",
    Urgente = "urgente",
}

export interface Expediente {
    id:     number;
    nombre: string;
}
