// Generated by https://quicktype.io

export interface Actuaciones {
    id:          number;
    nombre:      ActuacioneNombre;
    fecha:       string;
    descripcion: string;
    estado:      boolean;
    expediente:  ActuacioneExpediente;
}

export interface ActuacioneExpediente {
    id:           number;
    fecha:        string;
    numero:       string;
    materia:      string;
    estado:       boolean;
    responsable:  string;
    responsable2: null | string;
    descripcion:  string;
    condicion:    Condicion;
    precio:       number;
    consejeria:   string;
    expediente:   ExpedienteExpediente;
}

export enum Condicion {
    Confidencial = "confidencial",
    EnSeguimiento = "en seguimiento",
    Urgente = "urgente",
}

export interface ExpedienteExpediente {
    id:     number;
    nombre: ExpedienteNombre;
}

export enum ExpedienteNombre {
    Asi = "ASI",
    Inf = "INF",
    Jud = "JUD",
    Mo = "MO",
}

export enum ActuacioneNombre {
    CitacionYEmplazamiento = "Citacion y emplazamiento",
    Declaraciones = "Declaraciones",
    Informes = "Informes",
    Notificaciones = "Notificaciones",
    ResolucionesJudiciales = "Resoluciones judiciales",
}
